# Use an official Python runtime as a parent image
FROM python:3.11-slim-buster

# Set the working directory to /app
WORKDIR /app

RUN pip install --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install pandas==2.1.4 numpy==1.26.3 streamlit==1.30.0 tqdm==4.65.0

# Add the current directory contents into the container at /app
COPY . .

# Run the Streamlit app when the container launches
CMD streamlit run ui.py
